### ISSUE TITLE
Macro to make a key act as multiple modifiers

### ISSUE THREAD

**Issue by noctuid** [keyboardio/Kaleidoscope-Macros#15]
I'd like to create a key that acts as multiple modifiers at the same time. It seems that keys that are pressed down are automatically unpressed after a macro runs? I tried this:
```
if (keyToggledOn(keyState)) {
    return MACRO(D(LeftShift), D(LeftAlt), D(LeftControl));
} else if (keyToggledOff(keyState)) {
    return MACRO(U(LeftShift), U(LeftAlt), U(LeftControl));
}
```

Trying to hold the key bound to the corresponding macro and use it with other keys has no effect.

**Comment by algernon** [comment]
Keys are released because the report is cleared each cycle, and your macro has no case for when the key is held, it only has the toggle cases. If you change `keyToggledOn` to `keyIsPressed`, that should fix it.

Otherwise, [this post on the forum](https://community.keyboard.io/t/key-to-switch-to-specific-mac-app/440/15?u=algernon) is another way to accomplish the same thing. Add/remove modifiers as you see fit.

Hope this helps!

**Comment by algernon** [comment]
(On another note, we should likely have some docs on how key events work in Kaleidoscope, which should explain this report clearing business too.)

**Comment by noctuid** [comment]
Thanks! That does work as expected. I'm doing this because I have hotkeys bound to shift/control/alt combinations. This isn't really related, but unfortunately it looks like my hotkey daemon (sxhkd) incorrectly interprets my inputs when I have my keyboard layout as colemak with XKB. I have to press the keys that correspond to the QWERTY position of the keybinding I want to use. The keys show up correctly in xev and work with a different hotkey program (xchainkeys) though. Because of that I'm guessing this probably isn't kaleidoscope's problem. It seems strange that only in this case does my XKB remapping have any effect on my kaleidoscope remapping. Would you happen to have any insight on this issue or could you point me to any kaleidoscope-related information that might be useful to include in a bug report to sxhkd?

**Comment by algernon** [comment]
I'm afraid I can offer no help in this regard, I have next to no experience with remapping keys under X (even though I've been a Linux user since the late 90s, I never switched my layout from US-QWERTY, nor did any advanced key mappings on the OS side).

Sorry :(

What I can offer, is that I'll chime in as needed, and explain the Kaleidoscope part of things if need be, if you throw a bug report link my way.

**Comment by noctuid** [comment]
Thanks! I don't know if it will be necessary, but the issue is baskerville/sxhkd#108.
